In [1]:
import pandas as pd

In [14]:

df=pd.read_csv(r"C:\Users\Lakshya\Desktop\Python Projects\Python-Learning\numpy, pandas, matplotlib\Assets\4_handling_missing_data_fillna_dropna_interpolate\weather_data.csv", parse_dates=["day"], dayfirst=True)
#Set Day column as day datatype instead of String.

df.set_index("day", inplace=True)

df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-04-01          NaN        9.0   Sunny
2017-05-01         28.0        NaN    Snow
2017-06-01          NaN        7.0     NaN
2017-07-01         32.0        NaN    Rain
2017-08-01          NaN        NaN   Sunny
2017-09-01          NaN        NaN     NaN
2017-10-01         34.1        8.1  Cloudy
2017-11-01         40.0       12.0   Sunny

In [12]:
df.fillna(0)#,inplace=True) used when we want to modify it in actual df
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-04-01          0.0        9.0   Sunny
2017-05-01         28.0        0.0    Snow
2017-06-01          0.0        7.0       0
2017-07-01         32.0        0.0    Rain
2017-08-01          0.0        0.0   Sunny
2017-09-01          0.0        0.0       0
2017-10-01         34.1        8.1  Cloudy
2017-11-01         40.0       12.0   Sunny

In [15]:
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-04-01          NaN        9.0   Sunny
2017-05-01         28.0        NaN    Snow
2017-06-01          NaN        7.0     NaN
2017-07-01         32.0        NaN    Rain
2017-08-01          NaN        NaN   Sunny
2017-09-01          NaN        NaN     NaN
2017-10-01         34.1        8.1  Cloudy
2017-11-01         40.0       12.0   Sunny